# Generated by Django 6.0.7 on 2026-07-24 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='todo/')),
                ('taskType', models.CharField(choices=[('RG', 'Regular'), ('EDU', 'Education'), ('OFF', 'Office'), ('GK', 'General Knowledge')], default='RG', max_length=3)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
