# Generated by Django 6.0.7 on 2026-07-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assignedTo',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='completedAt',
            field=models.DateTimeField(default='2026-01-01'),
        ),
    ]
